#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : double-conversion
Version  : 3.1.0
Release  : 21
URL      : https://github.com/google/double-conversion/archive/3.1.0.tar.gz
Source0  : https://github.com/google/double-conversion/archive/3.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: double-conversion-lib
Requires: double-conversion-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons

%description
https://github.com/google/double-conversion
This project (double-conversion) provides binary-decimal and decimal-binary
routines for IEEE doubles.

%package dev
Summary: dev components for the double-conversion package.
Group: Development
Requires: double-conversion-lib
Provides: double-conversion-devel

%description dev
dev components for the double-conversion package.


%package lib
Summary: lib components for the double-conversion package.
Group: Libraries
Requires: double-conversion-license

%description lib
lib components for the double-conversion package.


%package license
Summary: license components for the double-conversion package.
Group: Default

%description license
license components for the double-conversion package.


%prep
%setup -q -n double-conversion-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536637251
mkdir -p clr-build
pushd clr-build
%cmake .. -DBUILD_SHARED_LIBS:BOOL=ON -DINSTALL_LIB_DIR=/usr/lib64
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1536637251
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/double-conversion
cp COPYING %{buildroot}/usr/share/doc/double-conversion/COPYING
cp LICENSE %{buildroot}/usr/share/doc/double-conversion/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/double-conversion/bignum.h
/usr/include/double-conversion/cached-powers.h
/usr/include/double-conversion/diy-fp.h
/usr/include/double-conversion/double-conversion.h
/usr/include/double-conversion/fast-dtoa.h
/usr/include/double-conversion/fixed-dtoa.h
/usr/include/double-conversion/ieee.h
/usr/include/double-conversion/strtod.h
/usr/include/double-conversion/utils.h
/usr/lib/cmake/double-conversion/double-conversionConfig.cmake
/usr/lib/cmake/double-conversion/double-conversionConfigVersion.cmake
/usr/lib/cmake/double-conversion/double-conversionTargets-relwithdebinfo.cmake
/usr/lib/cmake/double-conversion/double-conversionTargets.cmake

%files lib
%defattr(-,root,root,-)
/usr/lib/libdouble-conversion.so
/usr/lib/libdouble-conversion.so.3.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/double-conversion/COPYING
/usr/share/doc/double-conversion/LICENSE
