#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : double-conversion
Version  : 3.1.4
Release  : 25
URL      : https://github.com/google/double-conversion/archive/v3.1.4/double-conversion-3.1.4.tar.gz
Source0  : https://github.com/google/double-conversion/archive/v3.1.4/double-conversion-3.1.4.tar.gz
Summary  : Binary-decimal and decimal-binary routines for IEEE doubles
Group    : Development/Tools
License  : BSD-3-Clause
Requires: double-conversion-lib = %{version}-%{release}
Requires: double-conversion-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
Patch1: 0002-Use-GNUInstallDirs-to-install-files-in-the-expected-.patch

%description
https://github.com/google/double-conversion
This project (double-conversion) provides binary-decimal and decimal-binary
routines for IEEE doubles.

%package dev
Summary: dev components for the double-conversion package.
Group: Development
Requires: double-conversion-lib = %{version}-%{release}
Provides: double-conversion-devel = %{version}-%{release}
Requires: double-conversion = %{version}-%{release}

%description dev
dev components for the double-conversion package.


%package lib
Summary: lib components for the double-conversion package.
Group: Libraries
Requires: double-conversion-license = %{version}-%{release}

%description lib
lib components for the double-conversion package.


%package license
Summary: license components for the double-conversion package.
Group: Default

%description license
license components for the double-conversion package.


%prep
%setup -q -n double-conversion-3.1.4
%patch1 -p1
pushd ..
cp -a double-conversion-3.1.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557077271
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DBUILD_SHARED_LIBS:BOOL=ON -DINSTALL_LIB_DIR=/usr/lib64
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
%cmake .. -DBUILD_SHARED_LIBS:BOOL=ON -DINSTALL_LIB_DIR=/usr/lib64
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :
cd ../clr-build-avx2;
make test || : || :

%install
export SOURCE_DATE_EPOCH=1557077271
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/double-conversion
cp COPYING %{buildroot}/usr/share/package-licenses/double-conversion/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/double-conversion/LICENSE
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/double-conversion/bignum.h
/usr/include/double-conversion/cached-powers.h
/usr/include/double-conversion/diy-fp.h
/usr/include/double-conversion/double-conversion.h
/usr/include/double-conversion/fast-dtoa.h
/usr/include/double-conversion/fixed-dtoa.h
/usr/include/double-conversion/ieee.h
/usr/include/double-conversion/strtod.h
/usr/include/double-conversion/utils.h
/usr/lib64/cmake/double-conversion/double-conversionConfig.cmake
/usr/lib64/cmake/double-conversion/double-conversionConfigVersion.cmake
/usr/lib64/cmake/double-conversion/double-conversionTargets-relwithdebinfo.cmake
/usr/lib64/cmake/double-conversion/double-conversionTargets.cmake
/usr/lib64/haswell/libdouble-conversion.so
/usr/lib64/libdouble-conversion.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libdouble-conversion.so.3
/usr/lib64/haswell/libdouble-conversion.so.3.1.4
/usr/lib64/libdouble-conversion.so.3
/usr/lib64/libdouble-conversion.so.3.1.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/double-conversion/COPYING
/usr/share/package-licenses/double-conversion/LICENSE
